version: '3.8'

services:
  web:
    image: sammie119/nginx-php8.1-fpm-all-ex
    container_name: acts-nginx
    #restart: always
    ports:
        - "8080:8080"
    volumes:
        - ./src/public:/var/www/html
        - ./config/conf.d:/etc/nginx/conf.d
        - ./config/nginx.conf:/etc/nginx/nginx.conf
        # link data to storage area of the app.
        - ./data:/var/www/html/storage/salary_pdf

        - ./config/new-php.ini:/etc/php81/php.ini
        # - ./config/php_ini_conf.d:/etc/php81/conf.d
        # - ./config/php-fpm-settings.conf:/etc/php8/php-fpm.d/server.conf
    networks:
        - nginxphp

networks:
  nginxphp: